Repository pesto-students/batch-10-tripen, pull requests merged in 2019-09, with the labels that each got.

#6 setup: mono-repo
  .gitignore
  client/.gitignore
  client/README.md
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/yarn.lock
  package.json
  server/package.json
Labels: enhancement

#16 setup: add PR and Issue templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore, setup

#20 fix: circleci config.yml issue
  .circleci/config.yml
  server/index.js
  server/index.test.js
  server/package.json
  server/yarn.lock
Labels: blocking, bug

#23 setup: ignore package-lock.json and all .log files
  client/.gitignore
Labels: build, setup

#13 feat: setup server start, stop and folder structure
  package.json
  server/index.js
  server/package.json
  server/src/configs/env.js
  server/src/configs/server.js
  server/src/controllers/.keep
  server/src/middlewares/.keep
  server/src/models/.keep
  server/src/routes/.keep
  server/src/utils/.keep
  server/yarn.lock
  yarn.lock
Labels: backend, blocking, setup

#25 docs : fix incorrect link of Project Specs
  README.md
Labels: bug, documentation

#14 build: setup eslint, husky
  .eslintignore
  .eslintrc.json
  client/package.json
  package.json
Labels: setup

#36 fix: routes with switch ids & default path
  client/src/components/App.jsx
Labels: frontend

#29 feat: add server routes
  server/src/configs/server.js
  server/src/routes/.keep
  server/src/routes/api/index.js
  server/src/routes/api/v1/auth.js
  server/src/routes/api/v1/categories.js
  server/src/routes/api/v1/index.js
  server/src/routes/api/v1/index.test.js
  server/src/routes/api/v1/timeline.js
  server/src/routes/api/v1/user.js
  server/src/routes/index.js
  server/yarn.lock
Labels: backend, blocking, enhancement

#31 feat: add mongoose schemas in server/models
  server/src/models/.keep
  server/src/models/category.js
  server/src/models/post.js
  server/src/models/timeline.js
  server/src/models/user.js
  server/src/utils/.keep
  server/src/utils/constants.js
Labels: backend, enhancement

#55 fix: remove --frozen-lockfile and add updated yarn.lock
  .circleci/config.yml
  client/package.json
  client/yarn.lock
Labels: bug, build

#63 Prasham/refac atomic folder structure
  client/src/components/README.md
  client/src/components/atoms/README.md
  client/src/components/molecules/README.md
  client/src/components/organisms/README.md
  client/src/components/pages/README.md
  client/src/components/templates/README.md
Labels: documentation, frontend, setup

#74 fix: updated faulty eslint commands in package.json
  package.json
Labels: bug, build

#7 chore: create components and folder
  .circleci/config.yml
  client/.babelrc
  client/.gitignore
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/components/App.jsx
  client/src/components/App.test.js
  client/src/components/atoms/DateOfBirthPicker/DateOfBirthPicker.jsx
  client/src/components/molecules/EmailAndPassInput/EmailAndPassInput.jsx
  client/src/components/molecules/SignUpDetails/SignUpDetails.jsx
  client/src/components/molecules/TripCard/TripCard.jsx
  client/src/components/organisms/CoverImage/CoverImage.css
  client/src/components/organisms/CoverImage/CoverImage.jsx
  client/src/components/organisms/Header/Header.jsx
  client/src/components/organisms/Header/Header.test.js
  client/src/components/organisms/LoginModal/LoginModal.jsx
  client/src/components/organisms/LoginModal/LoginModal.test.js
  client/src/components/organisms/TimeLine/TimeLine.css
  client/src/components/organisms/TimeLine/TimeLine.jsx
  client/src/components/organisms/TripList/TripList.jsx
  client/src/components/pages/HomePage/HomePage.jsx
  client/src/components/pages/TimeLinePage/TimeLinePage.jsx
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/setupTests.js
  client/yarn-error.log
  client/yarn.lock
Labels: chore, frontend

#88 feat: Private Routes and other Routes
  client/package.json
  client/src/components/App.jsx
  client/src/components/molecules/PrivateRoute.jsx
  client/src/components/pages/Profile/index.jsx
  client/yarn.lock
Labels: enhancement, frontend

#92 setup deploy server
  .circleci/config.yml
  server/Procfile
  server/package.json
  server/src/configs/env.js
Labels: backend, setup

#97 feat: Profile page and unit test
  client/src/component/AuthorInfoSection/AuthorInfoSection.css
  client/src/component/AuthorInfoSection/AuthorInfoSection.test.jsx
  client/src/component/AuthorInfoSection/index.jsx
  client/src/component/AuthorTimelines/AuthorTimelines.css
  client/src/component/AuthorTimelines/AuthorTimelines.test.jsx
  client/src/component/AuthorTimelines/index.jsx
  client/src/component/InputBox/index.jsx
  client/src/component/TimelineCard/TimelineCard.test.jsx
  client/src/component/TimelineCard/index.jsx
  client/src/component/TimelineList/TimelineList.test.jsx
  client/src/component/TimelineList/index.jsx
  client/src/components/App.jsx
  client/src/components/pages/Profile/index.jsx
  client/src/containers/Profile/fetchProfileData.js
  client/src/containers/Profile/index.jsx
  client/src/index.jsx
  client/src/views/Profile.jsx
  client/src/views/ProfileView.test.jsx
  yarn.lock
Labels: chore, enhancement, frontend

#94 feat-proxy in react "package.json"
  client/package.json
  client/yarn-error.log
Labels: frontend

#68 feat:middleware timeline
  server/.babelrc
  server/package.json
  server/src/middlewares/README.md
  server/src/middlewares/timeline.js
  server/src/middlewares/timeline.test.js
  server/src/models/timeline.js
  server/src/routes/api/v1/timeline.js
  server/yarn.lock
Labels: backend, setup, tests

#95 added 404 page
  client/package.json
  client/src/components/App.jsx
  client/src/components/organisms/Header/Header.jsx
  client/src/components/organisms/LoginModal/LoginModal.jsx
  client/src/components/pages/NotFound/NotFound.jsx
  client/yarn.lock
Labels: frontend
