Repository pesto-students/batch-10-tripen, pull requests merged in 2019-10, with the labels that each got.

#105 fix:update timeline model
  server/src/models/timeline.js
Labels: backend, chore

#107 fix: Netlify Routes error
  client/public/_redirects
Labels: bug, chore, enhancement, frontend

#86 feat-crud timeline, DAO added
  server/.babelrc
  server/index.js
  server/src/configs/database.js
  server/src/configs/dbtest.js
  server/src/configs/server.js
  server/src/controllers/timeline.js
  server/src/controllers/timeline.test.js
  server/src/daos/timeline.js
  server/src/middlewares/printRoute.js
  server/src/models/timeline.js
  server/src/routes/api/v1/timeline.js
  server/src/utils/constants.js
  server/src/utils/dummyData.js
  server/yarn.lock
Labels: backend, setup

#111 feat: modify route, new validations, test files
  server/src/middlewares/README.md
  server/src/middlewares/timeline.js
  server/src/middlewares/timeline.test.js
  server/src/models/timeline.js
  server/src/routes/api/v1/timeline.js
Labels: backend, chore, documentation

#87 feat: add controllers, tests and helpers for auth
  .gitignore
  server/.babelrc
  server/package.json
  server/src/configs/env.js
  server/src/configs/server.js
  server/src/controllers/.keep
  server/src/controllers/v1/auth.js
  server/src/controllers/v1/auth.test.js
  server/src/controllers/v1/user.js
  server/src/middlewares/.keep
  server/src/middlewares/auth.js
  server/src/models/user.js
  server/src/routes/api/v1/auth.js
  server/src/utils/destructureUser.js
  server/src/utils/errorMessage.js
  server/src/utils/helpers/jwtHelper.js
  server/src/utils/statusMessage.js
  server/src/utils/validations/addErrorIfNotValid.js
  server/src/utils/validations/common/checkEmpty.js
  server/src/utils/validations/common/checkIfNotGeoJson.js
  server/src/utils/validations/common/checkString.js
  server/src/utils/validations/common/isEmail.js
  server/src/utils/validations/common/isEmpty.js
  server/src/utils/validations/forgotPassword.js
  server/src/utils/validations/mapErrorsToProperties.js
  server/src/utils/validations/signin.js
  server/src/utils/validations/signup.js
  server/yarn.lock
  yarn.lock
Labels: backend, enhancement

#104 chore: Fix and Home Page and Trending timelines
  client/src/component/AuthorTimelines/AuthorTimelines.test.jsx
  client/src/component/LoadingIndicator/index.jsx
  client/src/component/TimelineCard/TimelineCard.test.jsx
  client/src/component/TimelineCard/index.jsx
  client/src/component/TimelineList/TimelineList.test.jsx
  client/src/component/TimelineList/index.jsx
  client/src/components/App.jsx
  client/src/containers/Home/fetchTimelines.js
  client/src/containers/Home/index.jsx
  client/src/utils/getLastUpdatedTime.js
  client/src/views/Home.jsx
  client/src/views/HomeView.test.jsx
Labels: chore, enhancement, frontend

#113 feat: add routes, controllers and validations for user API
  server/package.json
  server/src/controllers/v1/README.md
  server/src/controllers/v1/user.js
  server/src/middlewares/auth.js
  server/src/middlewares/user.js
  server/src/routes/api/v1/user.js
  server/src/utils/helpers/jwtHelper.js
  server/yarn.lock
  yarn.lock
Labels: backend, enhancement

#117 fix: shift auth controllers to mongodb-memory-server
  server/src/controllers/v1/auth.test.js
Labels: backend, blocking, build

#118 chore-fetch timelines by user cntl,route,dao
  server/src/controllers/v1/timeline.js
  server/src/controllers/v1/timeline.test.js
  server/src/daos/timeline.js
  server/src/middlewares/auth.js
  server/src/middlewares/timeline.js
  server/src/routes/api/v1/timeline.js
Labels: backend, chore

#112 feat:added new middleware posts CRUD
  server/src/controllers/v1/timeline.test.js
  server/src/middlewares/timeline.js
  server/src/models/post.js
  server/src/routes/api/v1/timeline.js
Labels: backend, enhancement

#121 fix: /timeline/all/:userid GET functionality
  server/src/controllers/v1/timeline.js
  server/src/daos/timeline.js
  server/src/middlewares/auth.js
  server/src/middlewares/timeline.test.js
  server/src/routes/api/v1/timeline.js
Labels: backend, blocking, bug

#78 feat- auth context
  .gitignore
  client/package.json
  client/public/index.html
  client/src/components/App.jsx
  client/src/components/atoms/LogoutButton/LogoutButton.jsx
  client/src/components/molecules/Alerts/Alerts.jsx
  client/src/components/molecules/EmailAndPassInput/EmailAndPassInput.jsx
  client/src/components/molecules/SignInDetails/SignInDetails.jsx
  client/src/components/molecules/SignUpDetails/SignUpDetails.jsx
  client/src/components/molecules/TripCard/TripCard.jsx
  client/src/components/organisms/Header/Header.jsx
  client/src/components/organisms/Header/Header.test.js
  client/src/components/organisms/LoginModal/LoginModal.jsx
  client/src/components/organisms/LoginModal/LoginModal.test.js
  client/src/context/alert/AlertState.jsx
  client/src/context/alert/alertContext.js
  client/src/context/alert/alertReducer.js
  client/src/context/auth/AuthState.jsx
  client/src/context/auth/authContext.js
  client/src/context/auth/authReducer.js
  client/src/context/types.js
  client/src/index.jsx
  client/src/setupTests.js
  client/src/utils/setAuthToken.js
  client/yarn.lock
  package.json
  server/yarn.lock
  yarn.lock
Labels: chore, frontend

#129 feat: Profile Page server integration
  .gitignore
  client/src/component/AuthorInfoSection/index.jsx
  client/src/component/AuthorTimelines/index.jsx
  client/src/component/DefaultProfileImg/index.jsx
  client/src/component/LoadingIndicator/index.jsx
  client/src/components/organisms/Header/Header.jsx
  client/src/containers/Profile/fetchLoggedInUserTimelines.js
  client/src/containers/Profile/fetchProfileData.js
  client/src/containers/Profile/fetchPublicProfileData.js
  client/src/containers/Profile/index.jsx
  client/src/containers/Profile/updateProfileData.js
  client/src/context/auth/AuthState.jsx
  client/src/context/auth/authReducer.js
  client/src/serverUrl.js
  client/src/views/Profile.jsx
  server/yarn.lock
Labels: chore, enhancement, frontend

#126 fix: correct heroku push rejections
  server/package.json
  server/yarn.lock
Labels: build, chore

#130 fix: change location property from geoJSON to string
  server/src/models/category.js
  server/src/models/post.js
  server/src/models/timeline.js
  server/src/models/user.js
  server/src/utils/validations/signup.js
Labels: backend, refactor

#131 feat: frontend validations for sign up & login-form.
  client/src/components/molecules/SignInDetails/SignInDetails.jsx
  client/src/components/molecules/SignUpDetails/SignUpDetails.jsx
Labels: chore, frontend

#134 chore: homepage server integration
  client/src/containers/Home/fetchTimelines.js
Labels: chore, frontend

#135 feat-update user token on update
  server/src/controllers/v1/user.js
  server/src/daos/timeline.js
Labels: backend, chore

#139 passing client tests
  client/src/component/AuthorInfoSection/AuthorInfoSection.test.jsx
  client/src/component/AuthorTimelines/AuthorTimelines.test.jsx
  client/src/containers/Home/fetchTimelines.js
  client/src/views/Profile.jsx
  client/src/views/ProfileView.test.jsx
Labels: chore, frontend

#146 feat: update and refac user controllers
  server/src/controllers/v1/auth.test.js
  server/src/controllers/v1/user.js
  server/src/middlewares/user.js
  server/src/models/user.js
  server/src/routes/api/v1/user.js
  server/src/utils/helpers/jwtHelper.js
Labels: backend, bug, enhancement
